fix dev deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,13 +2,13 @@ name: Node.js CI/CD with Docker
 
 on:
   push:
-    branches: 
-      - "main"
-      - "dev"
+    branches:
+      - 'main'
+      - 'dev'
   pull_request:
-    branches: 
-      - "main"
-      - "dev"
+    branches:
+      - 'main'
+      - 'dev'
 
 jobs:
   build-and-deploy:
@@ -27,60 +27,60 @@ jobs:
       APP_PORT: ${{ vars.APP_PORT }}
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ env.DOCKERHUB_USERNAME }}
-        password: ${{ env.DOCKERHUB_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ env.DOCKERHUB_USERNAME }}
+          password: ${{ env.DOCKERHUB_PASSWORD }}
 
-    - name: Determine Image Tag Based on Branch
-      run: |
-        if [[ "${{ github.ref_name }}" == "main" ]]; then
-          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
-          echo "CONTAINER_NAME=titomeet-backend" >> $GITHUB_ENV
-          echo "APP_PORT=5000" >> $GITHUB_ENV
-        elif [[ "${{ github.ref_name }}" == "dev" ]]; then
-          echo "IMAGE_TAG=dev" >> $GITHUB_ENV
-          echo "CONTAINER_NAME=titomeet-backend-dev" >> $GITHUB_ENV
-          echo "APP_PORT=5001" >> $GITHUB_ENV
-        fi
+      - name: Determine Image Tag Based on Branch
+        run: |
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
+            echo "CONTAINER_NAME=titomeet-backend" >> $GITHUB_ENV
+            echo "APP_PORT=5001" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
+            echo "CONTAINER_NAME=titomeet-backend-dev" >> $GITHUB_ENV
+            echo "APP_PORT=5002" >> $GITHUB_ENV
+          fi
 
-    - name: Debug Variables
-      run: |
-        echo "DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}"
-        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"
-        echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}"
-        echo "APP_PORT=${{ env.APP_PORT }}"
+      - name: Debug Variables
+        run: |
+          echo "DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}"
+          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"
+          echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}"
+          echo "APP_PORT=${{ env.APP_PORT }}"
 
-    - name: Build and Push Docker Image
-      run: |
-        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
-        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
+      - name: Build and Push Docker Image
+        run: |
+          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
+          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
 
-    - name: Deploy to VPS
-      uses: appleboy/ssh-action@v0.1.1
-      with:
-        host: ${{ env.VPS_HOST }}
-        username: ${{ env.VPS_USER }}
-        key: ${{ env.VPS_PRIVATE_KEY }}
-        script: |
+      - name: Deploy to VPS
+        uses: appleboy/ssh-action@v0.1.1
+        with:
+          host: ${{ env.VPS_HOST }}
+          username: ${{ env.VPS_USER }}
+          key: ${{ env.VPS_PRIVATE_KEY }}
+          script: |
 
-          # Pull latest image from Docker Hub
-          docker pull ${{ env.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
-          
-          # Stop and remove old container if exists
-          docker stop ${{ env.CONTAINER_NAME }} || true
-          docker rm ${{ env.CONTAINER_NAME }} || true
+            # Pull latest image from Docker Hub
+            docker pull ${{ env.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
 
-          # Navigate to the deploy path
-          cd ${{ env.DEPLOY_PATH }}
+            # Stop and remove old container if exists
+            docker stop ${{ env.CONTAINER_NAME }} || true
+            docker rm ${{ env.CONTAINER_NAME }} || true
 
-          # Run the new container with environment variables
-          docker run -d --name ${{env.CONTAINER_NAME}} --env-file .env -p ${{env.APP_PORT}}:5000 ${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
-          # Clean up old Docker images
-          docker image prune -f
+            # Navigate to the deploy path
+            cd ${{ env.DEPLOY_PATH }}
+
+            # Run the new container with environment variables
+            docker run -d --name ${{env.CONTAINER_NAME}} --env-file .env -p ${{env.APP_PORT}}:5000 ${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
+            # Clean up old Docker images
+            docker image prune -f
